version: "3"

services:
  app:
    build:
      context: .
      args:
        - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
        - REACT_APP_PUBLIC_VAPID_KEY=${REACT_APP_PUBLIC_VAPID_KEY}
        - REACT_APP_ENCRYPTION_KEY=${REACT_APP_ENCRYPTION_KEY}
    ports:
      - "8001:8001"
    image: ps1242/devops:latest
    restart: always
