version: "3"

services:
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  server:
    build:
      context: ./server
    ports:
      - "8001:8001"
    restart: always
  client:
    build:
      context: ./client
      args:
        REACT_APP_PUBLIC_URL: ${REACT_APP_PUBLIC_URL}
        REACT_APP_CLIENT_ID: ${REACT_APP_CLIENT_ID}
    ports:
      - "8000:8000"
    restart: always
  model:
    build:
      context: ./model
    ports:
      - "8002:8002"
    restart: always
