version: "3"

services:
  app:
    environment:
      - REACT_APP_PUBLIC_URL=${REACT_APP_PUBLIC_URL}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_PUBLIC_URL: ${REACT_APP_PUBLIC_URL}
        REACT_APP_CLIENT_ID: ${REACT_APP_CLIENT_ID}
    ports:
      - "8001:8001"
    image: ps1242/devops:latest
    restart: always
