version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_PUBLIC_URL=${REACT_APP_PUBLIC_URL}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
    ports:
      - "8001:8001"
    image: ps1242/devops:latest
    restart: always
