version: "3"

services:
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  server:
    build:
      context: ./server
    ports:
      - "8001:8001"
    restart: always
  client:
    build:
      context: ./client
    ports:
      - "8000:8000"
    restart: always
