name: Continuous Deployment to Staging

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          namespace: devops-pratyush1712

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: react-express
          timeout: 8m
