name: Okteto Staging Deployment
on:
  push:
    branches: ["master"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Okteto
        uses: okteto/action-login@v1
        with:
          okteto_token: ${{ secrets.OKTETO_TOKEN }}
      - name: Build and Deploy
        uses: okteto/action-deploy@v1
        with:
          manifest_path: docker-compose.yml
          stack: staging
