name: Deploying to Staging

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to staging
        env:
          OKTETO_TOKEN: ${{ secrets.OKTETO_TOKEN }}
        run: |
          okteto namespace pratyush1712
          sh -c "okteto up"
