name: Continuous Integration

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        steps: ["lint", "build-client", "build-server", "docker-build"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        if: matrix.steps != 'docker-build'
        run: yarn install

      - name: Check Linter - TypeScript
        if: matrix.steps == 'lint'
        run: yarn run lint

      - name: Check Linter - Python
        if: matrix.steps == 'lint'
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

      - name: Build Client
        if: matrix.steps == 'build-client'
        working-directory: client
        run: CI='' yarn run build

      - name: Build Server
        if: matrix.steps == 'build-server'
        working-directory: server
        run: CI='' yarn run build
