name: Continuous Integration

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        steps: ["lint", "build-client", "build-server", "docker-build"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            client/
            server/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check Linter
        if: matrix.steps == 'lint'
        run: yarn run lint

      - name: Build Client
        if: matrix.steps == 'build-client'
        working-directory: client
        run: yarn run build

      - name: Build Server
        if: matrix.steps == 'build-server'
        working-directory: server
        run: yarn run build

      - name: Check for containerizability
        if: matrix.steps == 'docker-build'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          labels: |
            com.github.actions.description="Check for containerizability"
            com.github.actions.icon="check-circle"
            com.github.actions.color="green"
