name: Retrain model with updated dataset

on:
  schedule:
    - cron: "* 3 * * 3" # Runs every Wednesdat at 1:13 AM

jobs:
  create-and-commit-file:
    runs-on: ubuntu-latest
    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }} 
      SPOTIFY_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: ./model/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Retrain model
        working-directory: ./model/
        run: |
          python src/model.py
      
      - name: Commit model
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: Retrain model with updated data
          committer_name: TrainBot
          committer_email: actions@github.com
