name: Retrain model with updated dataset

on:
  schedule:
    - cron: "* 2 * * 3" # Runs every Wednesdat at 1:13 AM

jobs:
  create-and-commit-file:
    runs-on: ubuntu-latest
    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }} 
      SPOTIFY_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: ./model/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create and commit file
        working-directory: ./model/
        run: |
          python src/model.py
          git config --global user.name "Pratyush Sudhakar"
          git config --global user.email "pratyushsudhakar03@gmail.com"
          git add .
          git commit -m "Retrained model with updated dataset"
          git push
