name: Retrain model with updated dataset

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at 00:00

jobs:
  create-and-commit-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }} 
      SPOTIFY_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: ./model/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Retrain model
        working-directory: ./model/
        run: |
          python src/model.py
      
      - name: Commit model
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Retrained Model with Updated Data
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: .
          repository: .

          # Optional. Tag name being created in the local repository and 
          # pushed to remote repository and defined branch.
          tagging_message: 'v1.0.0'
          status_options: '--untracked-files=no'
          add_options: '-u'
          push_options: '--force'
          skip_dirty_check: true
